
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://aqthuabdamoerxnnfzvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxdGh1YWJkYW1vZXJ4bm5menZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODA3MDAsImV4cCI6MjA2Mzg1NjcwMH0.ZH54GpeE6Hc7HsD1dVaqzcQewM3V4QfnIc94NyxOX2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
